apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: zen-db
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"zen-demo","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/pipeline":"test","apps.tanzu.vmware.com/workload-type":"web"},"name":"zen","namespace":"team-tanzu"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"env":[{"name":"SPRING_JPA_DATABASE_PLATFORM","value":"org.hibernate.dialect.PostgreSQLDialect"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/max-scale":"10","autoscaling.knative.dev/min-scale":"2","autoscaling.knative.dev/target":"10"}}],"serviceClaims":[{"name":"db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"zen-postgres-claim"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/Turbots/zen.git"}}}}
    autoscaling.knative.dev/max-scale: "10"
    autoscaling.knative.dev/min-scale: "2"
    autoscaling.knative.dev/target: "10"
  labels:
    app.kubernetes.io/part-of: zen-demo
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: zen
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: zen-postgres-claim
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: zen

