apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: zen-db
  annotations:
    autoscaling.knative.dev/max-scale: "10"
    autoscaling.knative.dev/min-scale: "2"
    autoscaling.knative.dev/target: "10"
  labels:
    app.kubernetes.io/part-of: zen-demo
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: zen
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: zen-postgres-claim
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: zen

