---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: supplychain-config
  namespace: team-tanzu
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/Turbots/tanzu-demo.git
      ref: origin/main
      subPath: config/supplychain
  template:
  - ytt: {}
  deploy:
  - kapp: {}
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: workloads
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/Turbots/tanzu-demo.git
      ref: origin/main
      subPath: config/workloads
  template:
  - ytt: {}
  deploy:
  - kapp: {}