apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: delivery-worker
spec:
  resources:
  - name: source-provider
    params:
    - default: default
      name: serviceAccount
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: delivery-source-template
  - deployment:
      resource: source-provider
    name: deployer
    params:
    - default: default
      name: serviceAccount
    templateRef:
      kind: ClusterDeploymentTemplate
      name: app-deploy
  selector:
    app.tanzu.vmware.com/deliverable-type: worker